services:
  shiny_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shiny_app_container
    
    image: clinsight_image
  
  shinyproxy:
    image: openanalytics/shinyproxy:latest
    container_name: shinyproxy_container
    volumes:
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    depends_on:
      - shiny_app
    restart: always
    environment:
      CLINSIGHT_IMAGE: clinsight_image 
    group_add:
      - 1001
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      # Map host port 8080 to nginx container port 80
      - "80:80"
    depends_on:
      - shiny_app
      - csp_listener
    restart: always
  
  csp_listener:
    build:
      context: ./listener # Build from the 'listener' directory
      dockerfile: Dockerfile
    container_name: csp_listener_container
    expose:
      - "5000" # Expose the listener port internally\
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    restart: always