# docker-compose.yml
version: '3.8'

services:
  shiny_app:
    # Use a build context to build the image from Dockerfile.shiny
    build:
      context: .
      dockerfile: Dockerfile
    # Name the container (optional, makes it easier to identify)
    container_name: shiny_app_container
    # Expose the port so other services (like Nginx) can access it
    # Note: We are NOT mapping this port to the host, only exposing it internally
    expose:
      - "3838"
    # Restart policy (optional)
    restart: always

  nginx:
    image: nginx:latest # Use the standard Nginx image from Docker Hub
    container_name: nginx_proxy_container
    volumes:
      # Mount our custom nginx config into the default nginx config directory
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      # Map host port 8080 to nginx container port 80
      # You can change 8080 to 80 if it's available on your host
      - "8080:80"
    depends_on:
      # Ensure the shiny_app service is started before Nginx
      - shiny_app
    # Restart policy (optional)
    restart: always