services:
  shiny_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shiny_app_container
    expose:
      - "3838"
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_container
    volumes:
      # Mount our custom nginx config into the default nginx config directory
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      # Map host port 8080 to nginx container port 80
      - "8080:80"
    depends_on:
      - shiny_app
    restart: always
  csp_listener:
    # Use a build context pointing to the listener Dockerfile
    build:
      context: ./listener # Build from the 'listener' directory
      dockerfile: Dockerfile
    container_name: csp_listener_container
    expose:
      - "5000" # Expose the listener port internally\
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    restart: always